# Blog Configuration
# This file configures the blog system for your portfolio
# See BLOG_CONFIG.md for detailed documentation

[blog]
title = "Personal Blog"
description = "Thoughts on web development, technology, design, and everything in between."
author = "John Doe"
author_profile = "https://github.com/NishikantaRay"
base_url = ""

[pagination]
# Number of posts to show per page (currently set to 6)
# All 4 posts should show on page 1 since 4 < 6
posts_per_page = 6
enabled = true

[settings]
enable_comments = true
enable_social_sharing = true
enable_search = true
enable_categories = true
enable_tags = true
enable_related_posts = true
default_image = "https://dummyimage.com/600x400/0066cc/ffffff&text=Blog+Post"

# Blog Posts
[[posts]]
id = "typescript-modern-web"
title = "Building Modern Web Applications with TypeScript"
description = "TypeScript has revolutionized the way we build web applications. Learn about best practices, implementation strategies, and why TypeScript has become essential for modern development."
date = "2024-10-12"
tags = ["TypeScript", "Web Development", "JavaScript", "Modern Web"]
category = "Development"
content_file = "typescript-modern-web.md"
author = "John Doe"
read_time = "8 min read"
featured = true
status = "published"
image = "https://dummyimage.com/600x400/0066cc/ffffff&text=TypeScript+Web"
repo_url = "https://github.com/NishikantaRay/typescript-examples"
demo_url = "https://typescript-demo.yoursite.dev"
license = "MIT"
contributors = ["John Doe", "Community Contributors"]
features = [
    "Type safety for large codebases",
    "Seamless integration with modern frameworks", 
    "Improved developer productivity",
    "Better tooling and editor support"
]
related_posts = ["minimal-design", "open-source-journey"]

[[posts]]
id = "minimal-design"
title = "The Art of Minimal Design"
description = "Exploring the philosophy and practice of minimal design in creating beautiful, functional user experiences that prioritize clarity and purpose."
date = "2024-10-08"
tags = ["Design", "UX/UI", "Philosophy", "Minimalism"]
category = "Design"
content_file = "minimal-design.md"
author = "John Doe"
read_time = "6 min read"
featured = false
status = "published"
image = "https://dummyimage.com/600x400/222/fff&text=Minimal+Design"
repo_url = "https://github.com/NishikantaRay/minimal-design-examples"
demo_url = "https://minimal-design.yoursite.dev"
license = "MIT"
contributors = ["John Doe"]
features = [
    "Focus on clarity and usability",
    "Reduction of visual clutter",
    "Enhanced user engagement",
    "Timeless design principles"
]
related_posts = ["typescript-modern-web"]

[[posts]]
id = "open-source-journey"
title = "My Journey into Open Source"
description = "From my first nervous pull request to becoming a maintainer, here's what I've learned about contributing to open source projects and building meaningful connections in the developer community."
date = "2024-09-28"
tags = ["Open Source", "Community", "Career", "Development"]
category = "Community"
content_file = "open-source-journey.md"
author = "John Doe"
read_time = "10 min read"
featured = true
status = "published"
image = "https://dummyimage.com/600x400/333/fff&text=Open+Source+Journey"
repo_url = "https://github.com/NishikantaRay/open-source-contributions"
demo_url = "https://opensource-journey.yoursite.dev"
license = "MIT"
contributors = ["John Doe", "Open Source Community"]
features = [
    "How to start contributing",
    "Building a network in OSS",
    "Learning from code reviews",
    "Growing as a maintainer"
]
related_posts = ["typescript-modern-web", "minimal-design"]

[[posts]]
id = "web-performance-optimization"
title = "Web Performance Optimization: Beyond the Basics"
description = "Deep dive into advanced web performance optimization techniques, from critical rendering path optimization to service worker strategies."
date = "2024-09-15"
tags = ["Performance", "Web Development", "Optimization", "Core Web Vitals"]
category = "Development"
content_file = "web-performance-optimization.md"
author = "John Doe"
read_time = "12 min read"
featured = false
status = "published"
image = "https://dummyimage.com/600x400/ff6b35/ffffff&text=Web+Performance"
repo_url = "https://github.com/NishikantaRay/web-performance-demos"
demo_url = "https://performance-demo.yoursite.dev"
license = "MIT"
contributors = ["John Doe"]
features = [
    "Critical rendering path optimization",
    "Service worker implementation",
    "Core Web Vitals improvement",
    "Advanced caching strategies"
]
related_posts = ["typescript-modern-web"]