# Resume Configuration - RENDERER WITH DUMMY DATA
# Configure your resume content from this single file

[personal]
name = "Alex Johnson"
title = "Senior Full Stack Developer"
phone = "+1-555-123-4567"
email = "alex.johnson@example.com"
website = "https://alexjohnson.dev"
github = "https://github.com/alexjohnson"
linkedin = "https://linkedin.com/in/alexjohnson"
location = "San Francisco, CA"

[summary]
text = "Innovative Full Stack Developer with 5+ years of experience building scalable web applications and leading development teams. Currently working at @techcorp and previously contributed to open-source projects at @startupxyz. Passionate about emerging technologies and mentoring junior developers."

# Company Mappings for @mentions
[companies]

[companies.techcorp]
mention = "@techcorp"
name = "TechCorp Solutions"
url = "https://techcorp.com"

[companies.startupxyz]
mention = "@startupxyz"
name = "StartupXYZ"
url = "https://startupxyz.io"

[companies.digitalagency]
mention = "@digitalagency"
name = "Digital Agency Pro"
url = "https://digitalagencypro.com"

[companies.innovatetech]
mention = "@innovatetech"
name = "InnovateTech Labs"
url = "https://innovatetech.labs"

# Work Experience Section
[[experience]]
position = "Senior Full Stack Developer"
company = "TechCorp Solutions"
company_url = "https://techcorp.com"
location = "San Francisco, CA"
start_date = "Mar 2022"
end_date = "present"
is_current = true
achievements = [
    "Led a team of 6 developers in building a microservices architecture that improved system scalability by 300%",
    "Implemented CI/CD pipelines using Docker and Kubernetes, reducing deployment time from 2 hours to 15 minutes",
    "Architected and developed a real-time analytics dashboard serving 10M+ daily active users",
    "Mentored 4 junior developers and conducted technical interviews for 20+ candidates"
]

[[experience]]
position = "Full Stack Developer"
company = "StartupXYZ"
company_url = "https://startupxyz.io"
location = "Austin, TX"
start_date = "Jun 2021"
end_date = "Feb 2022"
is_current = false
achievements = [
    "Built the complete MVP from scratch using React, Node.js, and PostgreSQL",
    "Integrated payment processing with Stripe, handling $500K+ in transactions",
    "Developed responsive web application with 99.9% uptime and sub-2s load times",
    "Collaborated with design team to implement pixel-perfect UI/UX designs"
]

[[experience]]
position = "Frontend Developer"
company = "Digital Agency Pro"
company_url = "https://digitalagencypro.com"
location = "Remote"
start_date = "Jan 2020"
end_date = "May 2021"
is_current = false
achievements = [
    "Delivered 15+ client projects including e-commerce platforms and corporate websites",
    "Optimized web performance achieving 95+ Google Lighthouse scores across all projects",
    "Implemented automated testing suite reducing bug reports by 60%",
    "Led frontend architecture decisions for a team of 3 developers"
]

[[experience]]
position = "Junior Web Developer"
company = "InnovateTech Labs"
company_url = "https://innovatetech.labs"
location = "New York, NY"
start_date = "Sep 2019"
end_date = "Dec 2019"
is_current = false
achievements = [
    "Developed interactive web components using modern JavaScript frameworks",
    "Collaborated on mobile-first responsive design implementations",
    "Participated in code reviews and improved code quality standards",
    "Contributed to documentation and developer onboarding processes"
]

# Projects Section
[[projects]]
name = "E-Commerce Platform (2024)"
description = "Built a full-featured e-commerce platform with advanced inventory management and analytics"
technologies = ["React", "Node.js", "MongoDB", "Stripe", "AWS"]
start_date = "2024"
end_date = "2024"
highlights = [
    "Handles 50K+ products with real-time inventory tracking",
    "Integrated multiple payment gateways and shipping providers",
    "Implemented advanced search and filtering with Elasticsearch",
    "Built admin dashboard with comprehensive analytics and reporting"
]

[[projects]]
name = "Task Management SaaS (2023)"
description = "Developed a collaborative task management application for remote teams"
technologies = ["Vue.js", "Express", "PostgreSQL", "Socket.io", "Docker"]
start_date = "2023"
end_date = "2023"
highlights = [
    "Real-time collaboration features with WebSocket implementation",
    "Multi-tenant architecture supporting 100+ organizations",
    "Advanced project analytics and time tracking capabilities",
    "Mobile-responsive design with offline functionality"
]

[[projects]]
name = "Open Source CSS Framework (2022)"
description = "Created and maintain a lightweight, utility-first CSS framework"
technologies = ["Sass", "PostCSS", "JavaScript", "Webpack"]
start_date = "2022"
end_date = "2024"
highlights = [
    "1000+ GitHub stars and 50+ contributors",
    "Used by 200+ projects in production",
    "Comprehensive documentation with interactive examples",
    "Automated build system with semantic versioning"
]

[[projects]]
name = "AI-Powered Analytics Dashboard (2021)"
description = "Built machine learning powered business intelligence dashboard"
technologies = ["Python", "TensorFlow", "React", "D3.js", "PostgreSQL"]
start_date = "2021"
end_date = "2021"
highlights = [
    "Implemented predictive analytics using machine learning models",
    "Interactive data visualizations with custom D3.js components",
    "Real-time data processing pipeline handling 1M+ events daily",
    "Advanced user permission system with role-based access control"
]

# Education Section
[[education]]
degree = "M.S. in Computer Science"
institution = "Stanford University"
institution_url = "https://stanford.edu"
location = "Stanford, CA"
graduation_year = "2019"
gpa = "3.8/4.0"
notes = "Specialization in Machine Learning and Web Technologies"

[[education]]
degree = "B.S. in Software Engineering"
institution = "University of California, Berkeley"
institution_url = "https://berkeley.edu"
location = "Berkeley, CA"
graduation_year = "2017"
gpa = "3.7/4.0"
notes = "Magna , Dean's List for 6 semesters"

[[education]]
degree = "Associate Degree in Computer Programming"
institution = "Community College of San Francisco"
institution_url = "https://ccsf.edu"
location = "San Francisco, CA"
graduation_year = "2015"
gpa = "3.9/4.0"
notes = "Valedictorian, Programming Excellence Award"

# Skills Section
[skills]

[skills.frontend]
category = "Frontend Development"
technologies = ["React", "Vue.js", "Angular", "TypeScript", "HTML5", "CSS3", "Sass", "Tailwind CSS"]

[skills.backend]
category = "Backend Development"
technologies = ["Node.js", "Python", "Django", "Express", "FastAPI", "GraphQL", "REST APIs"]

[skills.databases]
category = "Databases"
technologies = ["PostgreSQL", "MongoDB", "Redis", "MySQL", "Elasticsearch", "DynamoDB"]

[skills.cloud]
category = "Cloud & DevOps"
technologies = ["AWS", "Docker", "Kubernetes", "GitHub Actions", "Jenkins", "Terraform", "Nginx"]

[skills.tools]
category = "Development Tools"
technologies = ["Git", "VS Code", "Postman", "Figma", "Jira", "Slack", "Linear", "Notion"]

[skills.languages]
category = "Programming Languages"
technologies = ["JavaScript", "TypeScript", "Python", "Java", "Go", "Rust", "SQL"]

# Certifications & Achievements
[[achievements]]
title = "AWS Certified Solutions Architect"
issuer = "Amazon Web Services"
date = "2024"
type = "certification"
description = "Professional level certification for cloud architecture"

[[achievements]]
title = "Winner - TechCrunch Disrupt Hackathon"
issuer = "TechCrunch"
date = "2023"
type = "award"
description = "First place for innovative AI-powered developer tools"

[[achievements]]
title = "Google Developer Expert (Web Technologies)"
issuer = "Google"
date = "2023"
type = "recognition"
description = "Community leader and expert in modern web development"

[[achievements]]
title = "Open Source Contributor of the Year"
issuer = "GitHub"
date = "2022"
type = "award"
description = "Recognition for outstanding contributions to open source projects"

[[achievements]]
title = "Certified Kubernetes Administrator (CKA)"
issuer = "Cloud Native Computing Foundation"
date = "2022"
type = "certification"
description = "Expert-level Kubernetes administration certification"

[[achievements]]
title = "React Conference Speaker"
issuer = "React Conf 2021"
date = "2021"
type = "speaking"
description = "Presented on 'Advanced React Patterns for Scalable Applications'"

# Settings
[settings]
show_gpa = true
show_location = true
show_phone = false
date_format = "MMM YYYY"
max_achievements_per_section = 10
enable_share_button = true